allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
        maven { url 'https://maven.regulaforensics.com/RegulaDocumentReader' }
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

subprojects { subproject ->
    subproject.configurations.configureEach {
        resolutionStrategy {
            force 'com.squareup.okhttp3:okhttp:5.0.0-alpha.16'
            force 'com.squareup.okhttp3:logging-interceptor:5.0.0-alpha.16'
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
