# org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
# org.gradle.jvmargs=-Xmx6g -XX:MaxMetaspaceSize=2g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.jvmargs=-Xmx6g -XX:MaxMetaspaceSize=2g -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true
android.enableR8.fullMode=false

# Kotlin incremental compilation can break on Windows
# when source roots span different drives/paths (e.g. Pub cache vs project).
kotlin.incremental=false